# Generated by Django 5.0.6 on 2024-05-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_course_question_options_question_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='response',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
