# Generated by Django 5.0.6 on 2024-05-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_course_date_debut_course_date_fin_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
