# Generated by Django 5.0.6 on 2024-05-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_marks',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
