# Generated by Django 5.0.6 on 2024-06-06 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_result_soumis'),
        ('teacher', '0003_remove_teacher_salary_teacher_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uenseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='teacher.teacher'),
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='survey.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='uenseignement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uenseignement', to='survey.uenseignement'),
            preserve_default=False,
        ),
    ]
